# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MakerModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SakeModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maker', to='sake.MakerModel')),
            ],
        ),
        migrations.CreateModel(
            name='SakeTypeModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aroma', models.CharField(choices=[('FU', 'fruity'), ('SP', 'spicy'), ('FE', 'fresh'), ('RI', 'rich')], default='FU', max_length=2)),
                ('taste', models.CharField(choices=[('SW', 'fruity'), ('DR', 'spicy'), ('SO', 'fresh'), ('RI', 'rich')], default='SW', max_length=2)),
                ('sake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sake', to='sake.SakeModel')),
            ],
        ),
    ]
